# Synapse Homeserver Configuration
# This file configures the Matrix Synapse server

server_name: "matrix.ms.local"

# Database configuration
database:
  name: "psycopg2"
  args:
    user: "synapse"
    password: "your_secure_db_password_change_this"
    database: "synapse_db"
    host: "db"
    port: 5432
    cp_min: 5
    cp_max: 10

# Registration
enable_registration: true
enable_registration_without_verification: true
registration_shared_secret: "your_secure_registration_secret_32_chars_min"

# Security
macaroon_secret_key: "your_secure_macaroon_secret_key_32_chars_min"

# TLS (disabled for development)
no_tls: true

# Reporting
report_stats: false

# Listeners
listeners:
  - port: 8008
    bind_addresses: ['0.0.0.0']
    type: "http"
    tls: false
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false

  # Admin API
  - port: 8009
    bind_addresses: ['0.0.0.0']
    type: "http"
    tls: false
    x_forwarded: true
    resources:
      - names: [client]
        compress: false

# Media store
media_store_path: "/data/media_store"

# App services
app_service_config_files:
  - "/app_services/telegram-registration.yaml"
  - "/app_services/facebook-registration.yaml"
  - "/app_services/webhooks-registration.yaml"

# Rate limiting
rc_messages_per_second: 0.2
rc_message_burst_count: 10
federation_rc_messages_per_second: 1
federation_rc_messages_burst_count: 20

# Max upload size
max_upload_size: "50M"

# CORS configuration for Element web client
web_client_location: "https://element.localhost"

# Additional CORS settings
cors_config:
  - origin: "https://element.localhost"
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    headers: ["Authorization", "Content-Type", "X-Requested-With"]
    supports_credentials: true
